on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: HubSpot Deploy Action
         uses: HubSpot/hubspot-cms-deploy-action@v1.7
         with:
          src_dir: "workflow-test" 
          dest_dir: "workflow-test"
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
